### ISSUE TITLE
Patch release changed downstream bevy version

### ISSUE THREAD

**Issue by luca-della-vedova** [nilclass/bevy_stl#11]
Hi and thanks for the great crate!

I have been using the crate at version 0.7.0 for some time with Bevy 0.9 and noticed that recently a new version was released, 0.7.1, that targeted bevy 0.10.

The issue with this is that since it is detected as a patch release, when I ran `cargo update` on my local project it automatically updated form 0.7.0 to 0.7.1, which increased the target bevy release, pulled in bevy 0.10 and actually broke the build.
I fixed it by specifying `=0.7.0` in my `Cargo.toml` but I believe this kind of changes that break APIs should be released with a version bump (i.e. 0.7.0 -> 0.8.0) to avoid cargo updating them automatically, as well as communicating to the user that a major change was released.

**Comment by nilclass** [comment]
You're absolutely right - I must have been asleep when making the release...
I just published 0.7.2 (which is the same as 0.7.0, back to bevy 0.9) and will publish the updated version as 0.8.0.

Thanks so much for reporting!
